### ISSUE TITLE
Swift build error: rename error

### ISSUE THREAD

**Issue by wfilleman** [Zewo/Zewo#6] opened 2015-12-10 14:03 UTC
Hopefully I'm just doing something wrong, but when I pull this repo and build in Linux using "swift build" the cloning of packages seems to work, but after the SSL Package is cloned, I see this error:

swift-build: rename error: File exists (17): /src/Packages/CLibvenice -> /src/Packages/CLibvenice-0.1.0

I also followed the steps to install the three C libs as well.

Any ideas what I'm missing?

Wes

**Comment by codegefluester** [comment] 2015-12-19 23:31
+1, running into the same issue on Ubuntu 14.04 with the latest snapshot of Swift (December 18th)

**Comment by BenchR267** [comment] 2015-12-20 10:20
I had the same problem. It's an error the current version of SPM has, there is a bug ticket here: https://bugs.swift.org/browse/SR-166 . Please comment there that you have the same problem so that the priority can be increased. Also a fix: your project directory might be over $HOME so move it there or in a subdirectory of it.

**Comment by codegefluester** [comment] 2015-12-20 12:12
@BenchR267 Thanks for that, did you run into the same error after switching to a "local" directory in the VM?

```
/home/vagrant/projects/epoch-test/Packages/HTTP-0.1.2/Sources/Response+File.swift:25:8: error: missing required module 'CURIParser'
import Core
```

**Comment by BenchR267** [comment] 2015-12-20 12:23
@codegefluester no, in my case everything is working fine. Could you please delete your Packages/ and .build/ directory to make a completely clean build? If that is not working, please show me your Package.swift

**Comment by codegefluester** [comment] 2015-12-20 12:28
Just tried again in a fresh folder which is not a shared VM folder, `Package.swift` is the same basic one as in the readme. Maybe I am just doing something wrong or its another bug in the newest Swift snapshot from Friday. Thanks for the help!

```
import PackageDescription

let package = Package(
    dependencies: [
        .Package(url: "https://github.com/Zewo/Epoch.git", majorVersion: 0, minor: 1)
    ]
)
```

**Comment by BenchR267** [comment] 2015-12-20 15:28
You are right, it was/is a bug in SPM. @paulofaria fixed it. In my example it is working in an ubuntu vagrant with the newest swift snapshot. Could you please try it?

```
rm -rf Packages/
rm -rf .build/
swift build
```

It should work now as expected. The problem is that every package that uses the C-library needs to link it as a dependency.

**Comment by paulofaria** [comment] 2015-12-21 11:37
@codegefluester Can you check if it works, so I can close the issue? thanks!

**Comment by codegefluester** [comment] 2015-12-22 16:12
For me it worked after going back to the Swift snapshot of the 10th of December, the current one did not work for me.

**Comment by paulofaria** [comment] 2015-12-22 16:13
It is supposed to be fixed now. Did you clean the build leftovers and tried to build again?

**Closed as completed** 2015-12-23 02:13 UTC
